# Setup
title:               LeafedFox
tagline:             'software engineer | she/her ğŸ³ï¸â€âš§ï¸'
description:         'trans girl software engineer'
url:                 https://leafedfox.github.io
baseurl:             '/'
paginate:            5
paginate_path: "/blog/page:num"
permalink:           pretty

# About/contact
author:
  name:              LeafedFox
  url:               https://fedi.shorks.gay/@ellie
  email:             leafedfox@proton.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.2
google_analytics_id: #UA-XXXX-Y
